name: NASDAQ Bot
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # v3'ü v4 yaptım
      - name: Python Kurulumu
        uses: actions/setup-python@v5  # v4'ü v5 yaptım
        with:
          python-version: '3.10'
      - name: Kütüphaneleri Yükle
        run: pip install finvizfinance pandas requests yfinance
      - name: Botu Çalıştır
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }} # Burası çok kritik!
        run: python bot.py
